[package]
name = "api-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.7"
tokio-macros = "2.4.0"
tokio = { version = "1.39.3", features = ["rt", "rt-multi-thread", "macros"] }
futures = "0.3.30"